apiVersion: v1
kind: Pod
metadata:
  name: rhel-docker-pod
  namespace: seu-namespace-aqui
spec:
  hostNetwork: true
  containers:
  - name: rhel-docker
    image: 'redhat/ubi8:8.10-901.1717584420'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "--"]
    args:
    - |
      yum install -y sudo unzip nmap-ncat jq yum-utils podman-docker && \
      mkdir -p /home/sapcon/S4H/ && \
      cp -r /mnt/* /home/sapcon/S4H/ && \
      tail -f /dev/null
    volumeMounts:
    - name: azurefile-pvc
      mountPath: /mnt/
  volumes:
  - name: azurefile-pvc
    persistentVolumeClaim:
      claimName: azurefile-pvc