apiVersion: v1
kind: Pod
metadata:
  name: rhel-docker-pod
  namespace: sap-siem
spec:
  hostNetwork: true
  containers:
  - name: rhel-docker
    image: 'redhat/ubi8:8.10-901.1717584420'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "--"]
    args:
    - |
      yum install -y sudo unzip && \
      unzip /mnt/sdk/nwrfc750P_14-70002752.zip -d /tmp/nwrfcsdk/ && \
      tail -f /dev/null
    volumeMounts:
    - name: azurefile-pvc
      mountPath: /mnt/
  volumes:
  - name: azurefile-pvc
    persistentVolumeClaim:
      claimName: azurefile-pvc
